# Site settings
title: "daily-cool-stuff"
description: "반갑습니다"
baseurl:  # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: 
author: "Jaewan"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: 

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "vendor", "script"]

# Old jekyll-paginate pagination logic
paginate: 3
paginate_path: "/legacy/page:num/"
