# Site settings
title: "daily-cool-stuff"
description: "반갑습니다"
baseurl:  # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: 
author: "Jaewan"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: 

plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2

exclude: ["LICENSE", "README.md", "vendor", "script", "Gemfile", "Gemfile.lock"]

# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:title.html
